name: Generate 3D Profile Contributions

on:
  schedule:
    - cron: "0 */24 * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Profile Contributions
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: conf/github-profile-3d-contrib.json
          
      - name: Push SVGs to the output-3d Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
